# Generated by Selenium IDE - VERSÃO CORRIGIDA COM DEBUG
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, NoSuchElementException

class TestRelease():
  def setup_method(self, method):
    self.driver = webdriver.Edge()
    self.driver.implicitly_wait(2)
    self.vars = {}
  
  def teardown_method(self, method):
    import sys
    import traceback
    exc_type, exc_value, exc_tb = sys.exc_info()
    if exc_type:
      print("\n[ERRO NO TESTE]")
      traceback.print_exception(exc_type, exc_value, exc_tb)
      print("Navegador será fechado após o erro acima.\n")
    try:
      self.driver.quit()
    except:
      pass
  
  def wait_and_click(self, by, value, timeout=10):
    """Método auxiliar para esperar e clicar com segurança"""
    element = WebDriverWait(self.driver, timeout).until(
      EC.element_to_be_clickable((by, value))
    )
    element.click()
    return element
  
  def wait_and_send_keys(self, by, value, keys, timeout=10):
    """Método auxiliar para esperar e enviar texto com segurança"""
    element = WebDriverWait(self.driver, timeout).until(
      EC.presence_of_element_located((by, value))
    )
    element.send_keys(keys)
    return element
  
  def debug_page_elements(self, context=""):
    """Método de debug para listar elementos na página"""
    print(f"\n[DEBUG {context}]")
    try:
      items = self.driver.find_elements(By.CSS_SELECTOR, "[class*='hover']")
      print(f"  Elementos com 'hover': {len(items)}")
      for i, item in enumerate(items[:5], 1):
        print(f"    {i}. {item.get_attribute('class')}")
    except Exception as e:
      print(f"  Erro no debug: {e}")
  
  def test_release(self):
    print("\n=== Iniciando Release Test ===")
    
    # 1-2: Abrir e configurar janela
    self.driver.get("http://localhost:5173/login")
    self.driver.set_window_size(1382, 736)
    time.sleep(1)
    
    # 3-6: Login
    print("1. Fazendo login como leader...")
    self.wait_and_click(By.ID, "email")
    self.driver.find_element(By.ID, "email").send_keys("leader@manager.com")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    
    # Aguarda dashboard carregar
    WebDriverWait(self.driver, 10).until(
      EC.presence_of_element_located((By.CSS_SELECTOR, ".bg-white:nth-child(2) .font-semibold"))
    )
    time.sleep(1)
    
    # 7-18: Criar primeira transação (Entrada)
    print("2. Criando transação de entrada...")
    self.wait_and_click(By.CSS_SELECTOR, ".bg-white:nth-child(2) .font-semibold")
    time.sleep(0.5)
    
    self.wait_and_send_keys(By.ID, "descricao", "teste01")
    time.sleep(0.3)
    
    self.driver.find_element(By.ID, "valor").click()
    time.sleep(0.2)
    self.driver.find_element(By.ID, "valor").send_keys("10.50")
    self.driver.find_element(By.ID, "valor").send_keys(Keys.ENTER)
    time.sleep(0.3)
    
    self.driver.find_element(By.ID, "data").click()
    time.sleep(0.3)
    self.driver.find_element(By.ID, "data").send_keys("16102025")
    time.sleep(0.3)
    
    self.wait_and_click(By.ID, "categoria")
    dropdown = self.driver.find_element(By.ID, "categoria")
    dropdown.find_element(By.XPATH, "//option[. = 'Doação']").click()
    time.sleep(0.3)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn-primary")
    time.sleep(2)
    
    # 21-33: Criar segunda transação (Saída)
    print("3. Criando transação de saída...")
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(0.5)
    
    self.wait_and_click(By.LINK_TEXT, "Nova Transação")
    time.sleep(0.5)
    
    self.wait_and_click(By.ID, "tipo")
    dropdown = self.driver.find_element(By.ID, "tipo")
    dropdown.find_element(By.XPATH, "//option[. = 'Saída']").click()
    time.sleep(0.3)
    
    self.wait_and_send_keys(By.ID, "descricao", "teste02")
    time.sleep(0.3)
    
    self.wait_and_send_keys(By.ID, "valor", "50.50")
    time.sleep(0.3)
    
    self.driver.find_element(By.ID, "data").click()
    time.sleep(0.3)
    self.driver.find_element(By.ID, "data").send_keys("16092025")
    time.sleep(0.3)
    
    self.wait_and_click(By.ID, "categoria")
    dropdown = self.driver.find_element(By.ID, "categoria")
    dropdown.find_element(By.XPATH, "//option[. = 'Transporte']").click()
    time.sleep(0.3)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn-primary")
    time.sleep(2)
    
    # 35-41: Editar transação
    print("4. Editando transação...")
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(1)
    
    WebDriverWait(self.driver, 10).until(
      EC.presence_of_element_located((By.CSS_SELECTOR, ".hover\\3A bg-gray-50:nth-child(3)"))
    )
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".hover\\3A bg-gray-50:nth-child(3) .btn:nth-child(2) > .w-4")
    time.sleep(0.5)
    
    WebDriverWait(self.driver, 10).until(
      EC.presence_of_element_located((By.ID, "valor"))
    )
    time.sleep(0.5)
    
    valor_field = self.driver.find_element(By.ID, "valor")
    valor_field.clear()
    time.sleep(0.2)
    valor_field.send_keys("100.5")
    time.sleep(0.3)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn-primary")
    time.sleep(2)
    
    # 42-45: Navegar para Inventário
    print("5. Navegando para Inventário...")
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(5) > .font-medium")
    time.sleep(1)
    
    WebDriverWait(self.driver, 10).until(
      EC.element_to_be_clickable((By.CSS_SELECTOR, ".justify-center > .w-5"))
    )
    time.sleep(1)
    
    # 46-57: Criar primeiro item
    print("6. Criando primeiro item do inventário...")
    self.wait_and_click(By.CSS_SELECTOR, ".justify-center > .w-5")
    time.sleep(0.5)
    
    WebDriverWait(self.driver, 10).until(
      EC.presence_of_element_located((By.ID, "nome"))
    )
    time.sleep(0.5)
    
    self.wait_and_send_keys(By.ID, "nome", "Teste Item 01")
    self.wait_and_send_keys(By.ID, "sku", "TS-ITEM-01")
    
    self.wait_and_click(By.ID, "categoria")
    dropdown = self.driver.find_element(By.ID, "categoria")
    dropdown.find_element(By.XPATH, "//option[. = 'Eletrônicos']").click()
    time.sleep(0.3)
    
    self.wait_and_send_keys(By.ID, "quantidade", "02")
    self.wait_and_send_keys(By.ID, "localizacao", "Sala teste")
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn-primary")
    time.sleep(2)
    
    # 58-71: Criar segundo item
    print("7. Criando segundo item do inventário...")
    self.wait_and_click(By.LINK_TEXT, "Novo Item")
    time.sleep(0.5)
    
    WebDriverWait(self.driver, 10).until(
      EC.presence_of_element_located((By.ID, "nome"))
    )
    
    self.wait_and_send_keys(By.ID, "nome", "Teste Item 02")
    self.wait_and_send_keys(By.ID, "sku", "TS-ITEM-02")
    self.wait_and_send_keys(By.ID, "quantidade", "04")
    
    self.wait_and_click(By.ID, "categoria")
    dropdown = self.driver.find_element(By.ID, "categoria")
    dropdown.find_element(By.XPATH, "//option[. = 'Ferramentas']").click()
    time.sleep(0.3)
    
    self.wait_and_send_keys(By.ID, "localizacao", "Sala 102")
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn-primary")
    time.sleep(2)
    
    # 72-78: Editar item
    print("8. Editando item do inventário...")
    WebDriverWait(self.driver, 10).until(
      EC.presence_of_element_located((By.CSS_SELECTOR, ".hover\\3A bg-gray-50:nth-child(2)"))
    )
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".hover\\3A bg-gray-50:nth-child(2) .btn:nth-child(2) > .w-4")
    time.sleep(0.5)
    
    WebDriverWait(self.driver, 10).until(
      EC.presence_of_element_located((By.ID, "localizacao"))
    )
    
    localizacao_field = self.driver.find_element(By.ID, "localizacao")
    localizacao_field.clear()
    time.sleep(0.2)
    localizacao_field.send_keys("Sala teste 02")
    time.sleep(0.3)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn-primary")
    time.sleep(2)  # Aguarda salvar edição
    
    # Volta para lista de inventário clicando no menu "Inventário"
    print("  Voltando para lista de inventário...")
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(5) > .font-medium")
    time.sleep(2)  # Aguarda lista carregar completamente
    
    # 79-82: Excluir item
    print("9. Excluindo item do inventário...")
    
    # Debug: mostra elementos disponíveis
    self.debug_page_elements("Antes de excluir item")
    
    # Aguarda a tabela/lista de itens carregar completamente
    print("  Aguardando lista de itens...")
    time.sleep(2)
    
    # CORREÇÃO: Tenta encontrar itens de forma mais flexível
    try:
      # Primeiro tenta encontrar qualquer linha de item
      WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, "[class*='hover'][class*='bg-gray']"))
      )
      time.sleep(1)
      
      # Procura todos os itens na lista
      items = self.driver.find_elements(By.CSS_SELECTOR, "[class*='hover'][class*='bg-gray']")
      print(f"  Encontrados {len(items)} itens na lista")
      
      if len(items) >= 2:
        # Tenta clicar no segundo item (índice 1)
        print("  Tentando excluir o segundo item...")
        delete_button = items[1].find_element(By.CSS_SELECTOR, ".btn:nth-child(3)")
        delete_button.click()
      else:
        # Fallback: tenta o seletor original
        print("  Usando seletor original...")
        self.wait_and_click(By.CSS_SELECTOR, ".hover\\3A bg-gray-50:nth-child(2) .btn:nth-child(3)")
      
    except TimeoutException:
      print("  [ERRO] Não foi possível encontrar itens na lista")
      self.debug_page_elements("Erro ao procurar itens")
      raise
    
    time.sleep(0.5)
    
    # Aguarda modal de confirmação e clica em confirmar
    WebDriverWait(self.driver, 5).until(
      EC.element_to_be_clickable((By.CSS_SELECTOR, ".btn-error:nth-child(1)"))
    )
    self.driver.find_element(By.CSS_SELECTOR, ".btn-error:nth-child(1)").click()
    time.sleep(2)
    
    # 83-87: Navegar e excluir transação
    print("10. Excluindo transação...")
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(4) > .font-medium")
    time.sleep(2)  # AUMENTADO
    
    # Debug antes de excluir transação
    self.debug_page_elements("Antes de excluir transação")
    
    # Aguarda lista de transações carregar
    try:
      WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".hover\\3A bg-gray-50:nth-child(4)"))
      )
    except TimeoutException:
      print("  [AVISO] Tentando encontrar transações de forma alternativa...")
      # Procura qualquer item de transação
      WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, "[class*='hover'][class*='bg-gray']"))
      )
    
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".hover\\3A bg-gray-50:nth-child(4) .btn:nth-child(3)")
    time.sleep(0.5)
    
    WebDriverWait(self.driver, 5).until(
      EC.element_to_be_clickable((By.CSS_SELECTOR, ".btn-error:nth-child(1)"))
    )
    self.driver.find_element(By.CSS_SELECTOR, ".btn-error:nth-child(1)").click()
    time.sleep(2)
    
    print("=== Teste concluído com sucesso! ===")