# Generated by Selenium IDE - Corrigido
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestado():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    self.wait = WebDriverWait(self.driver, 10)  # Wait padrão de 10 segundos
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_and_click(self, by, selector):
    """Espera elemento estar clicável e clica"""
    element = self.wait.until(EC.element_to_be_clickable((by, selector)))
    time.sleep(0.3)  # Pequeno delay adicional
    element.click()
    return element
  
  def wait_and_send_keys(self, by, selector, keys):
    """Espera elemento estar visível e envia texto"""
    element = self.wait.until(EC.visibility_of_element_located((by, selector)))
    time.sleep(0.3)
    element.clear()  # Limpa campo antes de digitar
    element.send_keys(keys)
    return element
  
  def test_testado(self):
    # Login
    self.driver.get("http://localhost:5173/login")
    self.driver.set_window_size(1382, 736)
    time.sleep(1)
    
    self.wait_and_click(By.ID, "email")
    self.wait_and_send_keys(By.ID, "email", "leaderteste@manager.com")
    time.sleep(0.5)
    
    self.wait_and_send_keys(By.ID, "password", "123456")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn")
    time.sleep(2)  # Espera login processar
    
    # Navegação para Arquivos
    self.wait_and_click(By.LINK_TEXT, "Arquivos")
    time.sleep(1.5)
    
   
    time.sleep(1)
    
    # ⚠️ ATENÇÃO: Upload de arquivo - NECESSITA CORREÇÃO
    # Se este é um input type="file", você precisa:
    # 1. Encontrar o input correto (provavelmente está oculto)
    # 2. Usar caminho ABSOLUTO do arquivo
    # Exemplo:
    # file_path = os.path.abspath("download/Teste.md")
    # file_input = self.driver.find_element(By.CSS_SELECTOR, "input[type='file']")
    # file_input.send_keys(file_path)
    
    # Upload de arquivo usando caminho absoluto na pasta Downloads
    try:
      file_input = self.wait.until(
        EC.presence_of_element_located((By.CSS_SELECTOR, "input[type='file']"))
      )
      file_path = os.path.join(os.path.expanduser("~"), "Downloads", "Teste.md")
      file_input.send_keys(file_path)
      time.sleep(1)
    except Exception as e:
      print(f"⚠️ ERRO: Não foi possível fazer upload. {e}")
      # Linha original que provavelmente não funciona:
      # self.driver.find_element(By.CSS_SELECTOR, ".hidden:nth-child(2)").send_keys("download/Teste.md")
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn-secondary")
    time.sleep(1.5)
    
    self.wait_and_send_keys(By.CSS_SELECTOR, ".input", "teste")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn:nth-child(4)")
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".text-gray-800")
    time.sleep(1)
    
    
    time.sleep(1)
    
    # ⚠️ ATENÇÃO: Segundo upload de arquivo
    try:
      file_input = self.wait.until(
        EC.presence_of_element_located((By.CSS_SELECTOR, "input[type='file']"))
      )
      file_path = os.path.join(os.path.expanduser("~"), "Downloads", "Teste2.md")
      file_input.send_keys(file_path)
      time.sleep(1)
    except Exception as e:
      print(f"⚠️ ERRO: Não foi possível fazer segundo upload. {e}")
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn-info > .w-4")
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".input")
    self.wait_and_send_keys(By.CSS_SELECTOR, ".input", "Teste02.md")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn:nth-child(4)")
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".px-2:nth-child(1)")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn:nth-child(3) path")
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn:nth-child(4)")
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".p-6")
    time.sleep(0.5)
    
    # Double click
    element = self.wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".p-6")))
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".hover\\3A bg-base-200:nth-child(6) > .font-medium")
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".py-2")
    time.sleep(1)
    
    # Preenchimento de formulário de teste
    self.wait_and_send_keys(By.ID, "titulo", "teste01")
    time.sleep(0.5)
    
    self.wait_and_send_keys(By.ID, "descricao", "teste")
    time.sleep(0.5)
    
    self.wait_and_send_keys(By.ID, "startDate", "2025-11-27")
    time.sleep(0.5)
    
    self.wait_and_send_keys(By.ID, "endDate", "2025-11-27")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".gap-3:nth-child(1) > .flex")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(2) > .flex > .w-8 > .text-sm")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(3) > .flex")
    time.sleep(0.5)
    
    self.wait_and_send_keys(By.CSS_SELECTOR, ".w-full:nth-child(1)", "teste")
    time.sleep(0.5)
    
    # Dropdown selection
    dropdown = self.wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, ".gap-2 > .flex-1")))
    time.sleep(0.3)
    dropdown.find_element(By.XPATH, "//option[. = 'membro02']").click()
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn-primary:nth-child(2)")
    time.sleep(1.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn-primary:nth-child(1)")
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".bg-primary\\/10:nth-child(6) > .font-medium")
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".sm\\3Apx-5")
    time.sleep(1)
    
    # Segundo formulário
    self.wait_and_send_keys(By.ID, "titulo", "teste02")
    time.sleep(0.5)
    
    self.wait_and_send_keys(By.ID, "startDate", "2025-11-28")
    time.sleep(0.5)
    
    self.wait_and_send_keys(By.ID, "endDate", "2025-11-28")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".gap-3:nth-child(1)")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(2) > .flex > .w-8")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn-primary:nth-child(1)")
    time.sleep(1.5)
    
    # Navegação para Calendário
    self.wait_and_click(By.LINK_TEXT, "CalendÃ¡rio")
    time.sleep(1.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".sm\\3Apx-5")
    time.sleep(1)
    
    # Terceiro formulário
    self.wait_and_send_keys(By.ID, "titulo", "teste03")
    time.sleep(0.5)
    
    self.wait_and_send_keys(By.ID, "descricao", "teste")
    time.sleep(0.5)
    
    self.wait_and_click(By.ID, "startDate")
    time.sleep(0.3)
    self.wait_and_send_keys(By.ID, "startDate", "2025-11-30")
    time.sleep(0.5)
    
    self.wait_and_send_keys(By.ID, "endDate", "2025-11-30")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".gap-3:nth-child(1) > .flex")
    time.sleep(0.5)
    
    # Scroll
    self.driver.execute_script("window.scrollTo(0,500)")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(3) > .flex")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(2) > .flex:nth-child(2) > .text-sm")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn-primary:nth-child(1)")
    time.sleep(1.5)
    
    # Edição
    self.wait_and_click(By.CSS_SELECTOR, ".btn-primary")
    time.sleep(1)
    
    self.wait_and_click(By.ID, "titulo")
    time.sleep(0.3)
    
    self.wait_and_click(By.ID, "descricao")
    self.wait_and_send_keys(By.ID, "descricao", "teste03")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(3) > .flex")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn-primary:nth-child(1)")
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn-error")
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn:nth-child(4)")
    time.sleep(1)
    
    # Logout e novo login
    self.wait_and_click(By.CSS_SELECTOR, ".hidden .w-6")
    time.sleep(1.5)
    
    self.wait_and_send_keys(By.ID, "email", "membro01@gmail.com")
    time.sleep(0.5)
    
    self.wait_and_send_keys(By.ID, "password", "123456")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn")
    time.sleep(2)
    
    # Navegação final
    self.wait_and_click(By.CSS_SELECTOR, ".hidden .flex:nth-child(4) > .font-medium")
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".group")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".text-gray-800")
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".hover\\3A bg-base-200:nth-child(5) > .font-medium")
    time.sleep(1)
    
    self.wait_and_click(By.CSS_SELECTOR, ".flex-1 > .text-gray-600")
    time.sleep(0.5)
    
    # Scroll e ações finais
    self.driver.execute_script("window.scrollTo(0,375)")
    time.sleep(0.5)
    
    element = self.wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".btn > .w-4 > path")))
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    time.sleep(0.3)
    
    element = self.wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".btn > .w-4")))
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn > .w-4")
    time.sleep(1)
    
    # Dropdown final
    dropdown = self.wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "div:nth-child(1) > .w-full")))
    time.sleep(0.3)
    dropdown.find_element(By.XPATH, "//option[. = 'Confirmado']").click()
    time.sleep(0.5)
    
    self.wait_and_click(By.CSS_SELECTOR, ".btn-primary")
    time.sleep(1)
    
    self.driver.execute_script("window.scrollTo(0,508)")
    time.sleep(1)
    
    print("✅ Teste concluído com sucesso!")