# Generated by Selenium IDE - Fixed Version
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.edge.service import Service
from selenium.webdriver.edge.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, NoAlertPresentException

class TestUntitled():
  def setup_method(self, method):
    # Configuração para Microsoft Edge
    edge_options = Options()
    edge_options.add_argument('--disable-blink-features=AutomationControlled')
    edge_options.add_experimental_option("excludeSwitches", ["enable-automation"])
    edge_options.add_experimental_option('useAutomationExtension', False)
    
    self.driver = webdriver.Edge(options=edge_options)
    self.driver.maximize_window()
    self.vars = {}
    self.wait = WebDriverWait(self.driver, 10)
  
  def teardown_method(self, method):
    time.sleep(2)
    self.driver.quit()
  
  def wait_and_click(self, by, selector, timeout=10):
    """Aguarda elemento estar clicável e clica"""
    element = self.wait.until(EC.element_to_be_clickable((by, selector)))
    time.sleep(0.5)
    element.click()
    time.sleep(0.5)
    return element
  
  def wait_and_send_keys(self, by, selector, keys, timeout=10):
    """Aguarda elemento estar visível e envia texto"""
    element = self.wait.until(EC.visibility_of_element_located((by, selector)))
    time.sleep(0.5)
    element.clear()
    element.send_keys(keys)
    time.sleep(0.5)
    return element
  
  def wait_for_alert(self, timeout=5):
    """Aguarda alert aparecer"""
    try:
      return self.wait.until(EC.alert_is_present())
    except TimeoutException:
      return None
  
  def test_untitled(self):
    try:
      # Login
      self.driver.get("http://localhost:5173/login")
      time.sleep(2)
      self.driver.set_window_size(1382, 736)
      time.sleep(1)
      
      self.wait_and_send_keys(By.ID, "email", "leaderteste@manager.com")
      self.wait_and_send_keys(By.ID, "password", "123456")
      self.wait_and_click(By.CSS_SELECTOR, ".btn")
      time.sleep(2)
      
      # Navegação e autenticação Google
      self.wait_and_click(By.CSS_SELECTOR, ".hidden .flex:nth-child(5) > .font-medium")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".btn-primary")
      time.sleep(2)
      
      # Processo de autenticação Google (se necessário)
      try:
        self.wait_and_click(By.CSS_SELECTOR, ".pGzURd")
        time.sleep(1)
        self.wait_and_click(By.CSS_SELECTOR, ".ksBjEc > .VfPpkd-RLmnJb")
        time.sleep(1)
        self.wait_and_click(By.CSS_SELECTOR, ".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-RLmnJb")
        time.sleep(2)
      except:
        pass  # Ignora se já estiver autenticado
      
      # Ações na aplicação
      self.wait_and_click(By.CSS_SELECTOR, ".sm\\3Apx-5")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".btn-secondary")
      time.sleep(1)
      
      self.wait_and_send_keys(By.CSS_SELECTOR, ".input", "teste")
      element = self.driver.find_element(By.CSS_SELECTOR, ".input")
      element.send_keys(Keys.ENTER)
      time.sleep(1)
      
      self.wait_and_click(By.CSS_SELECTOR, ".btn:nth-child(4)")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".text-gray-800")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".sm\\3Apx-5")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".btn-group > .btn-ghost")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".btn-ghost > .w-5")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".btn-info")
      time.sleep(1)
      
      # Criar arquivo
      self.wait_and_send_keys(By.CSS_SELECTOR, ".input", "testando01.md")
      self.wait_and_click(By.CSS_SELECTOR, ".btn:nth-child(4)")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".px-2:nth-child(1)")
      time.sleep(1)
      
      # Excluir arquivo com confirmação
      self.wait_and_click(By.CSS_SELECTOR, ".btn:nth-child(3) path")
      time.sleep(1)
      alert = self.wait_for_alert()
      if alert:
        assert alert.text == "Tem certeza que deseja excluir este arquivo?"
        alert.accept()
        time.sleep(1)
      
      # Calendário - Criar evento 1
      self.wait_and_click(By.LINK_TEXT, "Calendário")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".py-2")
      time.sleep(1)
      
      self.wait_and_send_keys(By.ID, "titulo", "teste01")
      self.wait_and_send_keys(By.ID, "descricao", "teste")
      self.wait_and_send_keys(By.ID, "startDate", "2025-11-24")
      self.wait_and_send_keys(By.ID, "endDate", "2025-11-24")
      time.sleep(1)
      
      self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(1) .w-8")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(3) > .flex")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(2) > .flex > .w-8 > .text-sm")
      time.sleep(1)
      
      # Adicionar participantes
      self.wait_and_send_keys(By.CSS_SELECTOR, ".w-full:nth-child(1)", "teste")
      dropdown = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".gap-2 > .flex-1")))
      time.sleep(0.5)
      dropdown.click()
      time.sleep(0.5)
      dropdown.find_element(By.XPATH, "//option[. = 'membro01']").click()
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".btn > .w-4")
      time.sleep(1)
      
      # Segundo participante
      self.wait_and_send_keys(By.CSS_SELECTOR, ".w-full:nth-child(1)", "teste")
      dropdown = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".gap-2 > .flex-1")))
      time.sleep(0.5)
      dropdown.click()
      time.sleep(0.5)
      dropdown.find_element(By.XPATH, "//option[. = 'membro02']").click()
      time.sleep(1)
      
      self.wait_and_click(By.CSS_SELECTOR, ".btn-primary:nth-child(2)")
      time.sleep(2)
      self.wait_and_click(By.CSS_SELECTOR, ".btn-primary:nth-child(1)")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".btn-primary")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".items-center:nth-child(2) .w-4")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".btn-primary:nth-child(1)")
      time.sleep(1)
      
      # Criar evento 2
      self.wait_and_click(By.CSS_SELECTOR, ".bg-primary\\/10:nth-child(6) > .font-medium")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".sm\\3Apx-5")
      time.sleep(1)
      
      self.wait_and_send_keys(By.ID, "titulo", "teste02")
      self.wait_and_send_keys(By.ID, "descricao", "teste")
      self.wait_and_send_keys(By.ID, "startDate", "2025-11-28")
      self.wait_and_send_keys(By.ID, "endDate", "2025-11-28")
      time.sleep(1)
      
      self.wait_and_click(By.CSS_SELECTOR, ".gap-3:nth-child(1) > .flex")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".btn-primary:nth-child(1)")
      time.sleep(2)
      
      # Criar evento 3
      self.wait_and_click(By.LINK_TEXT, "Calendário")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".bg-primary\\/10:nth-child(6) > .font-medium")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".sm\\3Apx-5")
      time.sleep(1)
      
      self.wait_and_send_keys(By.ID, "titulo", "teste03")
      self.wait_and_send_keys(By.ID, "descricao", "teste")
      self.wait_and_send_keys(By.ID, "startDate", "2025-11-29")
      self.wait_and_send_keys(By.ID, "endDate", "2025-11-29")
      time.sleep(1)
      
      self.wait_and_click(By.CSS_SELECTOR, ".gap-3:nth-child(1) > .flex")
      time.sleep(1)
      self.driver.execute_script("window.scrollTo(0,613)")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".btn-primary:nth-child(1)")
      time.sleep(1)
      
      # Excluir evento com confirmação
      self.wait_and_click(By.CSS_SELECTOR, ".btn-error")
      time.sleep(1)
      alert = self.wait_for_alert()
      if alert:
        assert alert.text == "Tem certeza que deseja excluir este evento?"
        alert.accept()
        time.sleep(1)
      
      # Logout e login com outro usuário
      self.wait_and_click(By.CSS_SELECTOR, ".hidden .w-6")
      time.sleep(1)
      self.driver.execute_script("window.scrollTo(0,0)")
      time.sleep(1)
      
      self.wait_and_send_keys(By.ID, "email", "membro01@manager.com")
      self.wait_and_send_keys(By.ID, "password", "123456")
      time.sleep(1)
      
      # Navegação como membro
      self.wait_and_click(By.LINK_TEXT, "Arquivos")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".group")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".text-gray-800")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".px-2:nth-child(1)")
      time.sleep(1)
      
      self.wait_and_click(By.LINK_TEXT, "Calendário")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".flex-1 > .text-gray-600")
      time.sleep(1)
      self.driver.execute_script("window.scrollTo(0,408)")
      time.sleep(1)
      
      self.wait_and_click(By.CSS_SELECTOR, ".btn-xs")
      time.sleep(1)
      
      # Atualizar status
      dropdown = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "div:nth-child(1) > .w-full")))
      time.sleep(0.5)
      dropdown.click()
      time.sleep(0.5)
      dropdown.find_element(By.XPATH, "//option[. = 'Confirmado']").click()
      time.sleep(1)
      
      self.wait_and_click(By.CSS_SELECTOR, ".btn-primary")
      time.sleep(1)
      self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(3) > .checkbox")
      time.sleep(2)
      
      print("✓ Teste executado com sucesso!")
      
    except Exception as e:
      print(f"✗ Erro durante execução do teste: {str(e)}")
      # Captura screenshot em caso de erro
      self.driver.save_screenshot("erro_teste.png")
      raise