# Generated by Selenium IDE - Corrigido com Datas Funcionando
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, NoSuchElementException, ElementClickInterceptedException

class TestTestado():
    def setup_method(self, method):
        self.driver = webdriver.Edge()
        self.vars = {}
        self.wait = WebDriverWait(self.driver, 10)
        self.step_number = 0
        self.debug_mode = True
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def debug_log(self, message, level="INFO"):
        """Sistema de debug melhorado"""
        if self.debug_mode:
            self.step_number += 1
            timestamp = time.strftime("%H:%M:%S")
            symbols = {"INFO": "ℹ️", "SUCCESS": "✅", "WARNING": "⚠️", "ERROR": "❌", "STEP": "🔹"}
            print(f"[{timestamp}] {symbols.get(level, '•')} Step {self.step_number}: {message}")
    
    def wait_and_click(self, by, selector, description=""):
        """Espera elemento estar clicável e clica com debug"""
        try:
            self.debug_log(f"Tentando clicar em: {description or selector}", "STEP")
            element = self.wait.until(EC.element_to_be_clickable((by, selector)))
            time.sleep(0.3)
            element.click()
            self.debug_log(f"Clique realizado: {description or selector}", "SUCCESS")
            return element
        except TimeoutException:
            self.debug_log(f"TIMEOUT ao esperar elemento: {selector}", "ERROR")
            raise
        except ElementClickInterceptedException:
            self.debug_log(f"Elemento bloqueado por outro: {selector}. Tentando scroll...", "WARNING")
            self.driver.execute_script("arguments[0].scrollIntoView(true);", element)
            time.sleep(0.5)
            element.click()
            self.debug_log(f"Clique após scroll: {description or selector}", "SUCCESS")
            return element
        except Exception as e:
            self.debug_log(f"ERRO ao clicar: {selector} - {str(e)}", "ERROR")
            raise
    
    def wait_and_send_keys(self, by, selector, keys, description=""):
        """Espera elemento estar visível e envia texto com debug"""
        try:
            self.debug_log(f"Tentando digitar em: {description or selector}", "STEP")
            element = self.wait.until(EC.visibility_of_element_located((by, selector)))
            time.sleep(0.3)
            element.clear()
            element.send_keys(keys)
            self.debug_log(f"Texto digitado: '{keys}' em {description or selector}", "SUCCESS")
            return element
        except TimeoutException:
            self.debug_log(f"TIMEOUT ao esperar campo: {selector}", "ERROR")
            raise
        except Exception as e:
            self.debug_log(f"ERRO ao digitar: {selector} - {str(e)}", "ERROR")
            raise
    
    def set_date_field(self, by, selector, date_value, description=""):
        """Define data em campo usando JavaScript - SOLUÇÃO CORRETA"""
        try:
            self.debug_log(f"Configurando data: {date_value} em {description or selector}", "STEP")
            element = self.wait.until(EC.element_to_be_clickable((by, selector)))
            element.click()
            time.sleep(0.2)
            element.clear()
            # Converter para formato dd/MM/yyyy se necessário
            if "-" in date_value:
                parts = date_value.split("-")
                date_value_fmt = f"{parts[2]}/{parts[1]}/{parts[0]}"
            else:
                date_value_fmt = date_value
            element.send_keys(date_value_fmt)
            time.sleep(0.2)
            element.send_keys(Keys.TAB)
            time.sleep(0.3)
            self.debug_log(f"Data configurada: {date_value_fmt}", "SUCCESS")
            return element
        except Exception as e:
            self.debug_log(f"ERRO ao configurar data: {str(e)}", "ERROR")
            raise
    
    def upload_file(self, file_name, description=""):
        """Upload de arquivo com verificação robusta"""
        try:
            self.debug_log(f"Iniciando upload: {file_name}", "STEP")
            
            file_input = self.wait.until(
                EC.presence_of_element_located((By.CSS_SELECTOR, "input[type='file']"))
            )
            
            file_path = os.path.join(os.path.expanduser("~"), "Downloads", file_name)
            
            if not os.path.exists(file_path):
                self.debug_log(f"ARQUIVO NÃO ENCONTRADO: {file_path}", "ERROR")
                raise FileNotFoundError(f"Arquivo não encontrado: {file_path}")
            
            self.debug_log(f"Arquivo encontrado: {file_path}", "INFO")
            file_input.send_keys(file_path)
            time.sleep(1)
            self.debug_log(f"Upload realizado: {file_name}", "SUCCESS")
            
        except FileNotFoundError as e:
            self.debug_log(str(e), "ERROR")
            raise
        except Exception as e:
            self.debug_log(f"ERRO no upload: {str(e)}", "ERROR")
            raise
    
    def select_dropdown_option(self, selector, option_text, description=""):
        """Seleciona opção em dropdown com debug"""
        try:
            self.debug_log(f"Selecionando '{option_text}' em dropdown", "STEP")
            dropdown = self.wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, selector)))
            time.sleep(0.3)
            dropdown.find_element(By.XPATH, f"//option[. = '{option_text}']").click()
            self.debug_log(f"Opção '{option_text}' selecionada", "SUCCESS")
            time.sleep(0.5)
        except Exception as e:
            self.debug_log(f"ERRO ao selecionar dropdown: {str(e)}", "ERROR")
            raise
    
    def test_testado(self):
        try:
            self.debug_log("=== INICIANDO TESTE ===", "INFO")
            
            # === LOGIN ===
            self.debug_log("FASE: Login", "INFO")
            self.driver.get("http://localhost:5173/login")
            self.driver.set_window_size(1366, 768)
            time.sleep(1)
            
            self.wait_and_click(By.ID, "email", "Campo Email")
            self.wait_and_send_keys(By.ID, "email", "leaderteste@manager.com", "Email do usuário")
            time.sleep(0.5)
            
            self.wait_and_send_keys(By.ID, "password", "123456", "Senha")
            time.sleep(0.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".btn", "Botão Login")
            time.sleep(2)
            
            # === NAVEGAÇÃO ARQUIVOS ===
            self.debug_log("FASE: Navegação para Arquivos", "INFO")
            self.wait_and_click(By.LINK_TEXT, "Arquivos", "Menu Arquivos")
            time.sleep(1.5)
            
            # === PRIMEIRO UPLOAD ===
            self.debug_log("FASE: Primeiro Upload", "INFO")
            self.upload_file("Teste.md", "Primeiro arquivo")
            
            self.wait_and_click(By.CSS_SELECTOR, ".btn-secondary", "Botão após upload")
            time.sleep(1.5)
            
            self.wait_and_send_keys(By.CSS_SELECTOR, ".input", "teste", "Campo de busca/input")
            time.sleep(0.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".btn:nth-child(4)", "Botão ação")
            time.sleep(1)
            
            self.wait_and_click(By.CSS_SELECTOR, ".text-gray-800", "Elemento texto")
            time.sleep(1)
            
            # === SEGUNDO UPLOAD ===
            self.debug_log("FASE: Segundo Upload", "INFO")
            self.upload_file("Teste2.md", "Segundo arquivo")
            
            self.wait_and_click(By.CSS_SELECTOR, ".btn-info > .w-4", "Botão info")
            time.sleep(1)
            
            self.wait_and_click(By.CSS_SELECTOR, ".input", "Input")
            self.wait_and_send_keys(By.CSS_SELECTOR, ".input", "Teste02.md", "Nome do arquivo")
            time.sleep(0.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".btn:nth-child(4)", "Confirmar")
            time.sleep(1)
            
            # === NAVEGAÇÃO CALENDÁRIO ===
            self.debug_log("FASE: Navegação para Calendário", "INFO")
            self.wait_and_click(By.LINK_TEXT, "Calendário", "Menu Calendário")
            time.sleep(1.5)
            self.wait_and_click(By.CSS_SELECTOR, ".py-2", "Item py-2")
            time.sleep(1)
            
            # === FORMULÁRIO 1 - COM DATAS CORRIGIDAS ===
            self.debug_log("FASE: Preenchimento Formulário 1", "INFO")
            self.wait_and_send_keys(By.ID, "titulo", "teste01", "Título 1")
            time.sleep(0.5)
            
            self.wait_and_send_keys(By.ID, "descricao", "teste", "Descrição")
            time.sleep(0.5)
            
            # CORREÇÃO AQUI: Usar método específico para datas
            self.set_date_field(By.ID, "startDate", "2025-11-27", "Data início")
            time.sleep(0.5)
            
            self.set_date_field(By.ID, "endDate", "2025-11-27", "Data fim")
            time.sleep(0.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".gap-3:nth-child(1) > .flex", "Opção 1")
            time.sleep(0.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(2) > .flex > .w-8 > .text-sm", "Opção 2")
            time.sleep(0.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(3) > .flex", "Opção 3")
            time.sleep(0.5)
            
            self.wait_and_send_keys(By.CSS_SELECTOR, ".w-full:nth-child(1)", "teste", "Campo w-full")
            time.sleep(0.5)
            
            self.select_dropdown_option(".gap-2 > .flex-1", "membro02", "Dropdown membro")
            
            self.wait_and_click(By.CSS_SELECTOR, ".btn-primary:nth-child(2)", "Botão primary 2")
            time.sleep(1.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".btn-primary:nth-child(1)", "Botão primary 1")
            time.sleep(5)
            
            self.wait_and_click(By.LINK_TEXT, "Calendário", "Menu Calendário")
            time.sleep(1.5)
            self.wait_and_click(By.CSS_SELECTOR, ".sm\\3Apx-5", "Botão calendário")
            time.sleep(1)
            
            
            # === FORMULÁRIO 2 - COM DATAS CORRIGIDAS ===
            self.debug_log("FASE: Preenchimento Formulário 2", "INFO")
            self.wait_and_send_keys(By.ID, "titulo", "teste02", "Título 2")
            time.sleep(0.5)
            
            self.set_date_field(By.ID, "startDate", "2025-11-28", "Data início 2")
            time.sleep(0.5)
            
            self.set_date_field(By.ID, "endDate", "2025-11-28", "Data fim 2")
            time.sleep(0.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".gap-3:nth-child(1)", "Gap-3")
            time.sleep(0.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(2) > .flex > .w-8", "Flex w-8")
            time.sleep(0.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".btn-primary:nth-child(1)", "Primary button")
            time.sleep(5)
            
            self.wait_and_click(By.LINK_TEXT, "Calendário", "Menu Calendário")
            time.sleep(1.5)
            self.wait_and_click(By.CSS_SELECTOR, ".sm\\3Apx-5", "Botão calendário")
            time.sleep(1)
            
            # === FORMULÁRIO 3 - COM DATAS CORRIGIDAS ===
            self.debug_log("FASE: Preenchimento Formulário 3", "INFO")
            self.wait_and_send_keys(By.ID, "titulo", "teste03", "Título 3")
            time.sleep(0.5)
            
            self.wait_and_send_keys(By.ID, "descricao", "teste", "Descrição 3")
            time.sleep(0.5)
            
            self.set_date_field(By.ID, "startDate", "2025-11-30", "Data início 3")
            time.sleep(0.5)
            
            self.set_date_field(By.ID, "endDate", "2025-11-30", "Data fim 3")
            time.sleep(0.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".gap-3:nth-child(1) > .flex", "Gap-3 flex")
            time.sleep(0.5)
            
            self.debug_log("Executando scroll", "INFO")
            self.driver.execute_script("window.scrollTo(0,500)")
            time.sleep(0.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(3) > .flex", "Flex child 3")
            time.sleep(0.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(2) > .flex:nth-child(2) > .text-sm", "Text-sm")
            time.sleep(0.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".btn-primary:nth-child(1)", "Salvar formulário 3")
            time.sleep(5)
            
            # === EDIÇÃO ===
            self.debug_log("FASE: Edição", "INFO")
            self.wait_and_click(By.CSS_SELECTOR, ".btn-primary", "Botão editar")
            time.sleep(1)
            
            self.wait_and_click(By.ID, "titulo", "Campo título edição")
            time.sleep(0.3)
            
            self.wait_and_click(By.ID, "descricao", "Campo descrição")
            self.wait_and_send_keys(By.ID, "descricao", "teste03", "Nova descrição")
            time.sleep(0.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".flex:nth-child(3) > .flex", "Opção flex")
            time.sleep(0.5)
            
            self.wait_and_click(By.CSS_SELECTOR, ".btn-primary:nth-child(1)", "Salvar edição")
            time.sleep(4)
            
            self.wait_and_click(By.CSS_SELECTOR, ".btn-error", "Botão error")
            time.sleep(1)
            
            self.wait_and_click(By.CSS_SELECTOR, ".btn:nth-child(4)", "Confirmar")
            time.sleep(5)
            
            # === LOGOUT E NOVO LOGIN ===
            self.debug_log("FASE: Logout e novo login", "INFO")
            self.wait_and_click(By.CSS_SELECTOR, ".hidden .w-6", "Botão logout")
            time.sleep(1.5)

            
            self.debug_log("=== TESTE CONCLUÍDO COM SUCESSO ===", "SUCCESS")
            
        except Exception as e:
            self.debug_log(f"TESTE FALHOU: {str(e)}", "ERROR")
            try:
                screenshot_path = f"error_screenshot_{int(time.time())}.png"
                self.driver.save_screenshot(screenshot_path)
                self.debug_log(f"Screenshot salvo: {screenshot_path}", "WARNING")
            except:
                pass
            raise