# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTeste01():
  def setup_method(self, method):
    # Usando Edge ao invés de Chrome para evitar popup de senha
    self.driver = webdriver.Edge()
    self.driver.implicitly_wait(2)  # Espera implícita de 2 segundos
    self.vars = {}
  
  def teardown_method(self, method):
    try:
      self.driver.quit()
    except:
      pass  # Ignora erros se o navegador já estiver fechado
  
  def test_teste01(self):
    print("\n=== Iniciando teste ===")
    self.driver.get("http://localhost:5173/login")
    self.driver.set_window_size(1382, 736)
    time.sleep(1)
    
    # Login
    print("1. Fazendo login como admin...")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("admin@manager.com")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    
    # Aguarda redirecionamento após login
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.LINK_TEXT, "Equipes"))
    )
    time.sleep(1)
    
    # Navega para Equipes
    print("2. Navegando para Equipes...")
    self.driver.find_element(By.LINK_TEXT, "Equipes").click()
    WebDriverWait(self.driver, 10).until(
      expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Nova Equipe"))
    )
    time.sleep(0.5)
    
    # Criar primeira equipe (BlackBee)
    print("3. Criando equipe BlackBee...")
    self.driver.find_element(By.LINK_TEXT, "Nova Equipe").click()
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.ID, "nome"))
    )
    time.sleep(0.5)
    
    self.driver.find_element(By.ID, "nome").click()
    self.driver.find_element(By.ID, "nome").send_keys("BlackBee")
    time.sleep(0.3)
    self.driver.find_element(By.ID, "descricao").send_keys("Drone")
    time.sleep(0.3)
    
    # Preenche a data clicando e digitando (formato DDMMAAAA sem barras)
    print("   Preenchendo data de criação...")
    self.driver.find_element(By.ID, "criadoEm").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "criadoEm").send_keys("20022021")
    time.sleep(0.5)
    
    print("   Submetendo formulário...")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    
    # Aguarda redirecionamento para lista
    WebDriverWait(self.driver, 10).until(
      expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".btn > .w-5"))
    )
    time.sleep(1)
    
    # Criar segunda equipe (teste)
    print("4. Criando equipe teste...")
    self.driver.find_element(By.CSS_SELECTOR, ".btn > .w-5").click()
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.ID, "nome"))
    )
    time.sleep(0.5)
    
    self.driver.find_element(By.ID, "nome").click()
    self.driver.find_element(By.ID, "nome").send_keys("teste")
    time.sleep(0.3)
    self.driver.find_element(By.ID, "descricao").send_keys("teste")
    time.sleep(0.3)
    
    # Preenche a data clicando e digitando (formato DDMMAAAA sem barras)
    self.driver.find_element(By.ID, "criadoEm").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "criadoEm").send_keys("15032022")
    time.sleep(0.5)
    
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    
    # Aguarda redirecionamento para lista de equipes
    print("5. Aguardando redirecionamento...")
    time.sleep(2)
    
    # Verifica se voltou para a lista e Membros está disponível
    WebDriverWait(self.driver, 10).until(
      expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Membros"))
    )
    time.sleep(1)
    
    # Navega para Membros
    print("6. Navegando para Membros...")
    self.driver.find_element(By.LINK_TEXT, "Membros").click()
    WebDriverWait(self.driver, 10).until(
      expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Novo Membro"))
    )
    time.sleep(0.5)
    
    # Criar membro líder
    print("7. Criando membro Lider01...")
    self.driver.find_element(By.LINK_TEXT, "Novo Membro").click()
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.ID, "nome"))
    )
    time.sleep(0.5)
    
    self.driver.find_element(By.ID, "nome").click()
    self.driver.find_element(By.ID, "nome").send_keys("Lider01")
    time.sleep(0.3)
    self.driver.find_element(By.ID, "matricula").click()
    self.driver.find_element(By.ID, "matricula").send_keys("2022001122")
    time.sleep(0.3)
    self.driver.find_element(By.ID, "email").send_keys("lider01@gmail.com")
    time.sleep(0.3)
    
    self.driver.find_element(By.ID, "curso").click()
    dropdown = self.driver.find_element(By.ID, "curso")
    dropdown.find_element(By.XPATH, "//option[. = 'Ciência da Computação']").click()
    time.sleep(0.3)
    
    self.driver.find_element(By.ID, "equipe").click()
    dropdown = self.driver.find_element(By.ID, "equipe")
    dropdown.find_element(By.XPATH, "//option[. = 'BlackBee']").click()
    time.sleep(0.3)
    
    self.driver.find_element(By.ID, "cargo").click()
    dropdown = self.driver.find_element(By.ID, "cargo")
    dropdown.find_element(By.XPATH, "//option[. = 'Líder']").click()
    time.sleep(0.3)
    
    # Preenche a data de início clicando e digitando (formato DDMMAAAA sem barras)
    self.driver.find_element(By.ID, "dataInicio").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "dataInicio").send_keys("18092025")
    time.sleep(0.5)
    
    self.driver.find_element(By.ID, "role").click()
    dropdown = self.driver.find_element(By.ID, "role")
    dropdown.find_element(By.XPATH, "//option[. = 'Líder - Gerencia sua equipe']").click()
    time.sleep(0.3)
    
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    
    # Aguarda redirecionamento após criar membro
    print("8. Aguardando redirecionamento após criar membro...")
    time.sleep(3)
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(1)
    
    # Navega para Equipes e exclui equipe "teste"
    print("9. Navegando para Equipes para excluir...")
    WebDriverWait(self.driver, 10).until(
      expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".flex:nth-child(3) > .font-medium"))
    )
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(3) > .font-medium").click()
    time.sleep(2)
    
    print("10. Excluindo equipe teste...")
    WebDriverWait(self.driver, 10).until(
      expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".bg-white:nth-child(4) .btn:nth-child(3) > .w-4"))
    )
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(4) .btn:nth-child(3) > .w-4").click()
    
    # Aguarda confirm de exclusão e aceita
    time.sleep(0.5)
    WebDriverWait(self.driver, 5).until(expected_conditions.alert_is_present())
    alert = self.driver.switch_to.alert
    # Aceita o confirm (não verifica texto pois pode variar)
    alert.accept()
    time.sleep(2)
    
    # Faz logout do admin
    print("11. Fazendo logout do admin...")
    time.sleep(1)
    WebDriverWait(self.driver, 10).until(
      expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".flex:nth-child(2) > .font-medium"))
    )
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(2) > .font-medium").click()
    time.sleep(1)
    
    WebDriverWait(self.driver, 10).until(
      expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".ml-3 path"))
    )
    self.driver.find_element(By.CSS_SELECTOR, ".ml-3 path").click()
    
    # Aguarda página de login
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.ID, "email"))
    )
    time.sleep(1)
    
    # Login como líder
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("lider01@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    
    # Aguarda dashboard carregar
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".bg-white"))
    )
    time.sleep(1)
    
    # Criar membro como líder
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white").click()
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.ID, "nome"))
    )
    time.sleep(0.5)
    
    self.driver.find_element(By.ID, "nome").click()
    self.driver.find_element(By.ID, "nome").send_keys("membro01")
    time.sleep(0.3)
    self.driver.find_element(By.ID, "matricula").send_keys("2022112233")
    time.sleep(0.3)
    self.driver.find_element(By.ID, "email").send_keys("membro01@gmail.com")
    time.sleep(0.3)
    
    self.driver.find_element(By.ID, "curso").click()
    dropdown = self.driver.find_element(By.ID, "curso")
    dropdown.find_element(By.XPATH, "//option[. = 'Física (Licenciatura)']").click()
    time.sleep(0.3)
    
    self.driver.find_element(By.ID, "cargo").click()
    dropdown = self.driver.find_element(By.ID, "cargo")
    dropdown.find_element(By.XPATH, "//option[. = 'Membro']").click()
    time.sleep(0.3)
    
    # Preenche a data de início clicando e digitando (formato DDMMAAAA sem barras)
    self.driver.find_element(By.ID, "dataInicio").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "dataInicio").send_keys("03102025")
    time.sleep(0.5)
    
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    
    # Aguarda redirecionamento
    time.sleep(2)
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(0.5)
    # Aguarda redirecionamento
    time.sleep(2)
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(0.5)
    
    # Navega para Equipes
    WebDriverWait(self.driver, 10).until(
      expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Equipes"))
    )
    self.driver.find_element(By.LINK_TEXT, "Equipes").click()
    time.sleep(1)
    
    # Faz logout
    self.driver.find_element(By.CSS_SELECTOR, ".ml-3").click()
    
    # Aguarda página de login
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.ID, "email"))
    )
    time.sleep(1)
    
    # Login como membro01
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("membro01@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    
    # Aguarda dashboard carregar
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.LINK_TEXT, "Membros"))
    )
    time.sleep(1)
    
    # Navega entre páginas
    self.driver.find_element(By.LINK_TEXT, "Membros").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Equipes").click()
    time.sleep(1)
    
    # Vai para configurações
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(4) > .font-medium").click()
    
    # Aguarda página de configurações
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.ID, "email"))
    )
    time.sleep(1)
    
    # Tenta alterar email (limpa o campo antes)
    print("12. Tentando alterar email do membro01...")
    try:
      email_field = self.driver.find_element(By.ID, "email")
      email_field.click()
      time.sleep(0.3)
      email_field.clear()
      time.sleep(0.3)
      email_field.send_keys("membro02@gmail.com")
      time.sleep(0.3)
      self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)").click()
      time.sleep(1.5)
    except Exception as e:
      print(f"   Erro ao tentar alterar email (esperado): {e}")
    
    # Faz logout
    print("13. Fazendo logout do membro01...")
    time.sleep(1)
    logout_button = WebDriverWait(self.driver, 10).until(
      expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".ml-3"))
    )
    logout_button.click()
    
    # Aguarda página de login
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.ID, "email"))
    )
    time.sleep(1)
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(0.5)
    
    # Tenta login com membro01 novamente
    self.driver.find_element(By.ID, "email").send_keys("membro01@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    
    # Aguarda dashboard
    time.sleep(2)
    
    # Tenta alterar email novamente (limpa o campo antes)
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.ID, "email"))
    )
    email_field = self.driver.find_element(By.ID, "email")
    email_field.click()
    time.sleep(0.3)
    email_field.clear()
    time.sleep(0.3)
    email_field.send_keys("membro02@gmail.com")
    time.sleep(0.3)
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    time.sleep(2)
  
