export const COURSES = [
  "Administração",
  "Ciência da Computação",
  "Ciências Atmosféricas",
  "Ciências Biológicas (Licenciatura)",
  "Design",
  "Engenharia Ambiental",
  "Engenharia Civil",
  "Engenharia de Bioprocessos",
  "Engenharia de Computação",
  "Engenharia de Controle e Automação",
  "Engenharia da Energia",
  "Engenharia de Materiais",
  "Engenharia de Produção",
  "Engenharia Elétrica",
  "Engenharia Eletrônica",
  "Engenharia Hídrica",
  "Engenharia Mecânica",
  "Engenharia Mecânica Aeronáutica",
  "Engenharia Química",
  "Física (Bacharelado)",
  "Física (Licenciatura)",
  "Matemática (Bacharelado)",
  "Matemática (Licenciatura)",
  "Química (Bacharelado)",
  "Química (Licenciatura)",
  "Sistemas de Informação",
] as const;
